version: '3'

services:
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-omoidasu}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - app-network
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
    image: fox20431/omoidasu-api:${VERSION}
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
