version: '3'

services:
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-omoidasu}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - app-network
  app:
    build:
        context: .
        dockerfile: Dockerfile
        args:
            - VERSION=${VERSION}
    image: fox20431/omoidasu-api:${VERSION}
#    environment:
#      - VERSION=${VERSION}
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
