name: Omoidasu API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Fetch the Dictionary
        run: |
          chmod +x fetch-dictionaries.sh
          . fetch-dictionaries.sh

      - name: Cache Dictionary File
        uses: actions/cache@v3
        with:
          path: src/main/resources/dicts
          key: ${{ runner.os }}-dictionary-${{ hashFiles('dictionary') }}
          restore-keys: |
            ${{ runner.os }}-dictionary-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
    
      - name: Build and Generate the Boot Jar
        run: |
          chmod +x gradlew
          ./gradlew build
          ./gradlew bootJar

      - name: Cache Project Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.m2/repository
          key: ${{ runner.os }}-deps-${{ hashFiles('dictionary') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag fox20431/omoidasu-api:$(date +%s)

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: |
            ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-